Repository kausalflow/hamilflow, pull requests merged in 2024-03, with the labels that each got.

#19 feat: use commitizen
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#21 feat(ops): #18 use commitizen
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#23 feat(model): add brownian motion
  docs/references/models/brownian_motion.md
  docs/tutorials/brownian_motion.py
  hamilflow/models/brownian_motion.py
  hamilflow/models/harmonic_oscillator.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  tests/test_models/test_brownian_motion.py
Labels: documentation, enhancement, model

#22 feat(model): #14 pendulum
  .gitignore
  docs/javascripts/mathjax.js
  docs/references/models/pendulum.md
  docs/tutorials/pendulum.py
  hamilflow/models/pendulum.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  tests/test_models/test_pendulum.py
Labels: enhancement, model

#43 fix(meta): #31 pre-commit warnings in the CI pipeline
  .github/workflows/docs-preview.yaml
  .github/workflows/docs-publish.yaml
  .github/workflows/publish.yaml
  .github/workflows/tests.yaml
  mkdocs.yml
Labels: bug, CI/CD
