Repository kausalflow/hamilflow, pull requests merged in 2024-09, with the labels that each got.

#95 chore(ruff): #94 enable all one-letter rules
  .pre-commit-config.yaml
  docs/tutorials/brownian_motion.py
  docs/tutorials/complex_harmonic_oscillator.py
  docs/tutorials/harmonic_oscillator_chain.py
  docs/tutorials/pendulum.py
  hamilflow/models/free_particle.py
  hamilflow/models/harmonic_oscillator.py
  hamilflow/models/harmonic_oscillator_chain.py
  hamilflow/models/kepler_problem/model.py
  hamilflow/models/pendulum.py
  pyproject.toml
  tests/models/kepler_problem/test_model.py
  tests/models/test_free_particle.py
  tests/models/test_harmonic_oscillator.py
  tests/models/test_harmonic_oscillator_chain.py
Labels: meta, CI/CD

#93 doc(Kepler problem): #83 add mathematical-physical descriptions
  docs/references/maths/trigonometrics.md
  docs/references/models/kepler_problem.md
  docs/references/models/kepler_problem/dynamics.md
  docs/references/models/kepler_problem/model.md
  docs/references/models/kepler_problem/numerics.md
  hamilflow/models/kepler_problem/__init__.py
  hamilflow/models/kepler_problem/dynamics.py
  hamilflow/models/kepler_problem/model.py
  mkdocs.yml
  tests/models/kepler_problem/test_dynamics.py
  tests/models/kepler_problem/test_model.py
Labels: documentation, model

#97 chore(ruff): #96 enable most less-controversial rules
  hamilflow/maths/trigonometrics.py
  hamilflow/models/brownian_motion.py
  hamilflow/models/free_particle.py
  hamilflow/models/harmonic_oscillator.py
  hamilflow/models/harmonic_oscillator_chain.py
  hamilflow/models/kepler_problem/dynamics.py
  hamilflow/models/kepler_problem/model.py
  hamilflow/models/kepler_problem/numerics.py
  hamilflow/models/pendulum.py
  hamilflow/models/utils/typing.py
  pyproject.toml
  tests/maths/test_trigonometrics.py
  tests/models/kepler_problem/conftest.py
  tests/models/kepler_problem/test_dynamics.py
  tests/models/kepler_problem/test_model.py
  tests/models/kepler_problem/test_numerics.py
  tests/models/test_brownian_motion.py
  tests/models/test_free_particle.py
  tests/models/test_harmonic_oscillator.py
  tests/models/test_harmonic_oscillator_chain.py
  tests/models/test_pendulum.py
Labels: meta, CI/CD

#98 doc(kepler-problem): #82 add tutorial
  docs/tutorials/kepler_problem.py
  hamilflow/models/kepler_problem/model.py
Labels: documentation
