Repository kausalflow/hamilflow, pull requests merged in 2024-08, with the labels that each got.

#79 chore(mypy): #78 use local mypy
  .pre-commit-config.yaml
  docs/tutorials/harmonic_oscillator_chain.py
  hamilflow/models/brownian_motion.py
  hamilflow/models/free_particle.py
  hamilflow/models/harmonic_oscillator.py
  hamilflow/models/harmonic_oscillator_chain.py
  hamilflow/models/pendulum.py
  poetry.lock
  pyproject.toml
  tests/test_models/test_harmonic_oscillator.py
  tests/test_models/test_harmonic_oscillator_chain.py
  tests/test_models/test_pendulum.py
Labels: enhancement, meta, CI/CD

#50 feat(central-field): add central force field model
  README.md
  docs/references/models/central_field.md
  docs/tutorials/central_force_motion.py
  docs/tutorials/index.md
  hamilflow/models/central_field.py
  mkdocs.yml
  pyproject.toml
  tests/test_models/test_central_field.py
Labels: documentation, model

#77 feat(model): #76 #51 #13 Kepler problem
  docs/references/models/central_field.md
  docs/references/models/kepler_problem.md
  docs/tutorials/kepler_problem.py
  hamilflow/maths/__init__.py
  hamilflow/maths/trigonometrics.py
  hamilflow/models/central_field.py
  hamilflow/models/kepler_problem/__init__.py
  hamilflow/models/kepler_problem/dynamics.py
  hamilflow/models/kepler_problem/model.py
  hamilflow/models/kepler_problem/numerics.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  tests/maths/__init__.py
  tests/maths/test_trigonometrics.py
  tests/models/__init__.py
  tests/models/kepler_problem/__init__.py
  tests/models/kepler_problem/conftest.py
  tests/models/kepler_problem/test_dynamics.py
  tests/models/kepler_problem/test_model.py
  tests/models/kepler_problem/test_numerics.py
  tests/models/test_brownian_motion.py
  tests/models/test_free_particle.py
  tests/models/test_harmonic_oscillator.py
  tests/models/test_harmonic_oscillator_chain.py
  tests/models/test_pendulum.py
  tests/test_models/test_central_field.py
Labels: documentation, enhancement, model

#91 chore(black): #90 update
  .pre-commit-config.yaml
Labels: meta, CI/CD

#88 doc: #81 comply with ruff pydocstyle (D)
  hamilflow/__init__.py
  hamilflow/maths/__init__.py
  hamilflow/maths/trigonometrics.py
  hamilflow/models/__init__.py
  hamilflow/models/brownian_motion.py
  hamilflow/models/free_particle.py
  hamilflow/models/harmonic_oscillator.py
  hamilflow/models/harmonic_oscillator_chain.py
  hamilflow/models/kepler_problem/__init__.py
  hamilflow/models/kepler_problem/dynamics.py
  hamilflow/models/kepler_problem/model.py
  hamilflow/models/kepler_problem/numerics.py
  hamilflow/models/pendulum.py
  hamilflow/models/utils/__init__.py
  hamilflow/models/utils/typing.py
  pyproject.toml
  tests/maths/__init__.py
  tests/maths/test_trigonometrics.py
  tests/models/__init__.py
  tests/models/kepler_problem/__init__.py
  tests/models/kepler_problem/conftest.py
  tests/models/kepler_problem/test_dynamics.py
  tests/models/kepler_problem/test_model.py
  tests/models/kepler_problem/test_numerics.py
  tests/models/test_brownian_motion.py
  tests/models/test_free_particle.py
  tests/models/test_harmonic_oscillator.py
  tests/models/test_harmonic_oscillator_chain.py
  tests/models/test_pendulum.py
Labels: documentation, CI/CD
